### ISSUE TITLE
How to change default token lifetime / expiry time ?

### ISSUE THREAD

**Issue by kutubjt** [qiutuleng/laravel-passport-phone-verification-code-grant#3]
How to change default token lifetime / expiry time for accessToken and refreshToken? I tried the below in the AuthServiceProvider.php boot method but it does not work.

```
// boot method of app\Providers\AuthServiceProvider.php
public function boot()
    {
        $this->registerPolicies();

        Passport::routes();
        Passport::tokensExpireIn(now()->addMinutes(5));
        Passport::refreshTokensExpireIn(now()->addDays(30));
    }
```

**Comment by qiutuleng** [comment]
@kutubjt 

Hi, I'm sorry I saw your Issue just now.


I've confirmed. This is a Bug, but no better solution has been found for the time being.
You can try this.

1. Add the `qiutuleng/laravel-passport-phone-verification-code-grant` to the `dont-discover` attribute in the `composer.json` file. 
   Example of code:

   ```json
   "extra": {
       "laravel": {
           "dont-discover": ["qiutuleng/laravel-passport-phone-verification-code-grant"]
       }
   },
   ```

   Example of image:
   ![Composer.json](https://tva1.sinaimg.cn/large/006y8mN6ly1g79uw4cbguj31te0pk41y.jpg)


2. you should run the `composer dumpautoload` command.
   Example of command:

   ```bash
   composer dumpautoload
   ```

   Example of image:
   ![Command](https://tva1.sinaimg.cn/large/006y8mN6ly1g79uw48rxij31bq0l6aez.jpg)


3. Add a `\QiuTuleng\PhoneVerificationCodeGrant\PhoneVerificationCodeGrantServiceProvider::class`  line to the `providers` attribute in the `config/app.php` file.  after the `App\Providers\AuthServiceProvider::class,` line.
   Example of Code:

   ```json
   //...
           /*
            * Application Service Providers...
            */
           // Service Provider with System or yourself...
           // App\Providers\AuthServiceProvider::class,
           \QiuTuleng\PhoneVerificationCodeGrant\PhoneVerificationCodeGrantServiceProvider::class,
   //...
   ```

   Example of image:
   ![app.php](https://tva1.sinaimg.cn/large/006y8mN6ly1g79uw44q0wj31q80l6q6s.jpg)

Done. It works for me.

![AuthServiceProvider.php](https://tva1.sinaimg.cn/large/006y8mN6ly1g79uw3pjw2j316m0qgju2.jpg)

![Postman](https://tva1.sinaimg.cn/large/006y8mN6ly1g79uw416bpj315v0u0kbk.jpg)
